- name: person
  hosts: localhost
  become: yes
  tasks:
  - name: print persion
    ansible.builtin.package:
      name: "{{item}}" #item is a default keyword
    loop: 
    - git
    - mysql
    - postfix
    